### ISSUE TITLE
Validação de Nota Acessando Apenas um Índice do Vetor papelMoeda - TicketMachine.java | Linha 25

### ISSUE THREAD

**Issue by dmsdy** [dmsdy/TicketMachine#1]
O loop for na função inserir está verificando apenas o índice 1 do array papelMoeda, em vez de comparar o valor correspondente do array (ou seja, papelMoeda[i]) com a quantidade inserida.

```if (papelMoeda[1] == quantia) {```

**Comment by Gaba0022** [comment]
Feito realizado a devida correção
