### ISSUE TITLE
Sobreposição de Informações ao Utilizar o Mesmo Índice de um Objeto Existente - Troco.java | Linha 44

### ISSUE THREAD

**Issue by dmsdy** [dmsdy/TicketMachine#2]
Erro na atribuição do valor referente à cédula de 2 reais, pois o índice utilizado para armazenar este valor no array papeisMoeda é o índice 1, que já está sendo utilizado para armazenar a cédula de 5 reais

```papeisMoeda[1] = new PapelMoeda(2, count);```

**Comment by Gaba0022** [comment]
Foi realizado as devidas correções
